routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('voitures', 'VoitureController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Voiture.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Voiture extends Model
{
    protected $fillable = [
        'marque',
        'modele',
        'annee',       
    ];

    public $timestamps = false;
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/VoitureController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Voiture;

class VoitureController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $voitures = Voiture::all();

        return view('index', compact('voitures'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('voitures.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'marque' => 'required',
            'modele' => 'required',
            'annee' => 'required'
        ]);
        $voiture = new Voiture([
            'marque' => $request->get('marque'),
            'modele' => $request->get('modele'),
            'annee' => $request->get('annee')
        ]);
        $voiture->save();
        return redirect('/voitures')->with('success', 'Nouvelle voiture enregistrée !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
		$voiture = Voiture::find($id);

		return View::make('voitures.show')
			->with('voiture', $voiture);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $voiture = Voiture::find($id);
        return view('voitures.edit', compact('voiture'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'marque' => 'required',
            'modele' => 'required',
            'annee' => 'required'
        ]);

        $voiture = Voiture::find($id);
        $voiture->marque =  $request->get('marque');
        $voiture->modele = $request->get('modele');
        $voiture->annee = $request->get('annee');
        $voiture->save();

        return redirect('/voitures')->with('success', 'Voiture modifiée !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $voiture = Voiture::find($id);
        $voiture->delete();

        return redirect('/voitures')->with('success', 'Voiture supprimée !');
    }
}

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laravel CRUD Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <header class="container-fluid p-3 mb-2 bg-dark text-white">
            <h1 class="text-center display-4">Application de gestion de voiture</h1>
            <!-- <img src="/voiture.jpg" alt="alt text"> -->
    </header>
    <div class="container">
        @yield('main')
    </div>
</body>

</html>

resources/views/index.blade.php
@extends('base')

@section('main')

<div class="row">
    <div class="col-sm-12">
        <div class='row'>
            <h1 class="display-4">Liste de voitures</h1>
            <div>
                <a style="margin: 18px;" href="{{ route('voitures.create')}}" class="btn btn-success">Nouvelle voiture</a>
            </div>
        </div>
        <table class="table table-striped">
            <thead>
                <tr class="p-3 mb-2 bg-dark text-white">
                    <td>ID</td>
                    <td>Marque</td>
                    <td>Modele</td>
                    <td>Année</td>
                    <td>Actions</td>
                </tr>
            </thead>
            <tbody>
                @foreach($voitures as $voiture)
                <tr>
                    <td>{{$voiture->id}}</td>
                    <td>{{$voiture->marque}}</td>
                    <td>{{$voiture->modele}}</td>
                    <td>{{$voiture->annee}}</td>
                    <td>
                        <a href="{{ route('voitures.edit',$voiture->id)}}" class="btn btn-primary">Modifier</a>
                        <form action="{{ route('voitures.destroy', $voiture->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">Supprimer</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div>
        </div>
        @endsection

        <div class="col-sm-12">

            @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
            @endif
        </div>

resources/views/voitures/create.blade.php
@extends('base')

@section('main')
<div class="row">
    <div class="container-fluid">
        <h1 class="display-4 text-left">Formulaire d'ajout de voiture</h1>
        <div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
            @endif
            <div class="col-sm-6">
                <form method="post" action="{{ route('voitures.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="marque">Marque :</label>
                        <input type="text" class="form-control" name="marque" />
                    </div>

                    <div class="form-group">
                        <label for="modele">Modèle :</label>
                        <input type="text" class="form-control" name="modele" />
                    </div>

                    <div class="form-group">
                        <label for="annee">Année :</label>
                        <input type="number" class="form-control" name="annee" value="2000" />
                    </div>

                    <button type="submit" class="btn btn-success float-right w-50">Validez</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/voitures/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Modifier une voiture</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('voitures.update', $voiture->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="marque">Marque :</label>
                <input type="text" class="form-control" name="marque" value={{ $voiture->marque }} />
            </div>

            <div class="form-group">
                <label for="modele">Modèle :</label>
                <input type="text" class="form-control" name="modele" value={{ $voiture->modele }} />
            </div>

            <div class="form-group">
                <label for="annee">Année :</label>
                <input type="number" class="form-control" name="annee" value={{ $voiture->annee }} />
            </div>
            
            <button type="submit" class="btn btn-primary">Modifier</button>
        </form>
    </div>
</div>
@endsection